# Generated by Django 6.1.1 on 2026-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
