# Generated by Django 6.1.1 on 2026-09-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_groupstudent_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'guruh', 'verbose_name_plural': 'guruhlar'},
        ),
    ]
